TrajectoryPlannerROS:
    acc_lim_x: 0.001
    acc_lim_y: 0.001
    acc_lim_theta: 1.0
    max_vel_x: 0.3
    min_vel_x: 0.1
    max_rotational_vel: 0.5
    min_in_place_rotational_vel: 0.1
    escape_vel: -0.2
    holonomic_robot: true
    meter_scoring: true

    xy_goal_tolerance: 0.2
    yaw_goal_tolerance: 0.2

    sim_time: 4.0
    sim_granularity: 0.04
    vx_samples: 5
    vtheta_samples: 20

    goal_distance_bias: 0.8
    path_distance_bias: 0.6
    occdist_scale: 0.01
    heading_lookahead: 0.325
    dwa: false

    oscillation_reset_dist: 0.01